#!/bin/bash
function getSuffix {
	commit="$(git log -n 1 -- "${1}" | grep "^commit" | sed "s/[^[:space:]]*[[:space:]]*\(.*\)/\1/")" 
	prefix="$(echo -n ${1} | tac | cut -d . -f 1 | tac)"
	suffix="$(echo -n ${1} | tac | cut -d . -f 2- | tac)"
	if [ "${prefix}" == "${suffix}" -o "${3}" == "-" ]
	then
		echo "${1}_${commit:0:${2:-7}}"
	else
		echo "${prefix}_${commit:0:${2:-7}}.${suffix}"
	fi
}

if [ "${2:---}" == "--" ]
then
	echo cp "${1}" "$(getSuffix "${1}" ${3})"
else
	echo cp "${1}" "${2}/$(basename $(getSuffix "${1}" ${3}))"
fi
